version: 2

models:

    - name: sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: identifier of orders 
            tests : 
            - not_null 

          - name: products_id
            description: identifier of products
            tests : 
            - not_null 

          - name: qty

          - name: turnover
            description: amount of income
            tests : 
            - not_null 

          - name: purchase_cost
            description: amount of costs
            tests : 
            - not_null 

          - name: margin
            description: turnover/purchase_cost